### ISSUE TITLE
Twitch login: Something went wrong

### ISSUE THREAD

**Issue by substantialaim** [TobiasPankner/Twitch-Unfollower#2]
I need help running this, I run into issues upon trying to login to twitch when the browser opens up.
It doesn't let me log in.

**Comment by substantialaim** [comment]
Something went wrong.
Please try again.


This error upon logging in.

**Comment by TobiasPankner** [comment]
Hey, where do you get this error? On the twitch page?

**Comment by substantialaim** [comment]
Yes browser opens, I go to log in to twitch and that error appears. Can you help me? & help me go through the steps. My twitch account is max 2k following :/

**Comment by substantialaim** [comment]
Do you have a discord?

**Comment by TobiasPankner** [comment]
Huh that seems like it would be an issue with twitch itself and not with this program.

Does the login work in a normal browser?

**Comment by TobiasPankner** [comment]
Please try opening a incognito tab and log into twitch there.

**Comment by substantialaim** [comment]
Login works normal browser yes

**Comment by TobiasPankner** [comment]
Which browser are you using?

**Comment by substantialaim** [comment]
It opens chrome for me ???

**Comment by substantialaim** [comment]
Chrome & I also have brave

**Comment by TobiasPankner** [comment]
I get the same error. I'll try to fix it asap

**Comment by substantialaim** [comment]
Thanks man, this would be legendary for me! :D
Ive got the same twitch account since 2016 but max following :(

**Comment by TobiasPankner** [comment]
Should be fixed now, please update the bot and reinstall the dependencies.
Would be great if you could let me know if it works

**Comment by substantialaim** [comment]
Started working, but then this happened - https://i.gyazo.com/c47327aa03d2931aadfc84bfb67cfac6.png

**Comment by substantialaim** [comment]
Does like 20 and then stops

**Comment by TobiasPankner** [comment]
What happened in the browser at the time of error?

**Comment by substantialaim** [comment]
The channels don't show, then I have to close everything and relog in and do everything again

**Comment by TobiasPankner** [comment]
Okay, I'll take a look

**Comment by substantialaim** [comment]
I worked out a small temp fix that worked, I had to scroll down to load about 200-400 channels & now the script is working perfectly.

So I had to preload the channels

**Comment by TobiasPankner** [comment]
Fixed in commit 70133a7
