### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Fadel2000gazal** [TobiasPankner/Twitch-Unfollower#3]
when I try to log in twitch shows this error message " Your browser is not currently supported. Please use a [recommended browser](https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers). "
is there anything I am doing wrong?

**Comment by TobiasPankner** [comment]
You are probably not doing anything wrong. Looks like twitch changed something on their end again.  
I'll take a look at it when I have some time

**Comment by Fadel2000gazal** [comment]
OK, Take your time

**Comment by TobiasPankner** [comment]
I completely rewrote the script to not use browser automation anymore.  
Please try again with the newest version (be aware of the new instruction in the readme!).

Let me know if it works as expected

**Comment by Fadel2000gazal** [comment]
I keep getting this error message " Error getting followed channels "

**Comment by TobiasPankner** [comment]
Weird, please try again with the newest version. It should log why it failed now

**Comment by Fadel2000gazal** [comment]
The error now is " Missing headers in headers.txt ". I am using windows, and Chrome browser. I tried to run the code with various **gql**s, but the problem is remaining. In addition, I checked all these on, just to make sure [Here](https://ibb.co/C8X0N6z)
these are the the lines that are in headers.txt 

```
POST /gql HTTP/1.1
Accept: 
Accept-Encoding: 
Accept-Language: 
Authorization: 
Client-Id: 
Client-Integrity: 
Client-Session-Id: 
Client-Version: 
Connection: 
Content-Length: 
Content-Type: 
Host: 
Origin: 
Referer: 
Sec-Fetch-Dest: 
Sec-Fetch-Mode: 
Sec-Fetch-Site: 
User-Agent: 
X-Device-Id: 
sec-ch-ua: 
sec-ch-ua-mobile: 
sec-ch-ua-platform: "Windows"
```

**Comment by TobiasPankner** [comment]
That looks good. Can you please put the code
`print(headers)`
in line 16 after `if not len(headers) == len(necessary_headers):`?
Then we can see what header is missing, make sure to redact the values as you did above

**Comment by Fadel2000gazal** [comment]
I am afraid to mess up your code because it is my first time dealing with python codes. Sorry

**Comment by TobiasPankner** [comment]
No worries. I just pushed a new version. Just pull and try again please

**Comment by Fadel2000gazal** [comment]
thats the new error
 ```
dict_keys([])
Missing headers in headers.txt
```

**Comment by TobiasPankner** [comment]
So it doesn't find any headers in the file. Very strange.
Can you upload the headers.txt file (without the values) here please? Then I can maybe recreate the error

**Comment by Fadel2000gazal** [comment]
ok

**Comment by TobiasPankner** [comment]
The "X-Device-Id" header seems to be missing. Try copying the headers of some other request

**Comment by Fadel2000gazal** [comment]
the same error is showing. this is my new headers.txt file
[headers.txt](https://github.com/TobiasPankner/Twitch-Unfollower/files/10202421/headers.txt)

**Comment by TobiasPankner** [comment]
I just tried with that exact file and it's working perfectly fine on my PC so I'm getting a bit despereate here.

With which program do you edit the file? Just the standard notepad in windows?

**Comment by Fadel2000gazal** [comment]
yes I am using the standard notepad in windows
I will delete this file for privacy.
> the same error is showing. this is my new headers.txt file

**Comment by TobiasPankner** [comment]
I fear you have to change your password as the file can still be downloaded.

**Comment by TobiasPankner** [comment]
I am kind of at my wits end here.
I have now added a log in the  program to see if it can even read the file correctly. 
Please try again, sorry

**Comment by TobiasPankner** [comment]
Another question, what python version are you using?
You can check with `python -V`

**Comment by Fadel2000gazal** [comment]
the same is happening, sorry for bothering you.
It might be problem from me, thanks for you hard work.

that's my python version
`Python 3.10.9`

**Comment by TobiasPankner** [comment]
Alright, I will try with this exact version and see if thats the problem

**Comment by TobiasPankner** [comment]
> the same is happening, sorry for bothering you. It might be problem from me, thanks for you hard work.
> 
> that's my python version `Python 3.10.9`

Do you still have the output of the program? Did it look like this?
![image](https://user-images.githubusercontent.com/39444749/206910785-974ae61e-a717-48ef-ae73-21501afc38e6.png)

**Comment by TobiasPankner** [comment]
The python version is also not the issue it seems. You could try it on another PC and see if that changes anything, sadly I don't have any other idea

**Comment by Fadel2000gazal** [comment]
IT IS WORKING
I was just stupid and I didn't think of saving the headers.txt file before ruining the program.
THANK YOU A LOT. Your codes is a life-saver

**Comment by TobiasPankner** [comment]
Oh wow! I didn't think of that haha
Great to hear, You're welcome!
